Improve errors for read-only array mutations
salesforce/observable-membrane pull request #63
Opened 2021-07-22 22:51 UTC by divmain

This PR addresses the unhelpful error message discussed in salesforce/lwc#1739, when an attempt is made at mutating a read-only array.  Some discussion seems to have occurred offline that wasn't captured in the issue, so the preferred solution wasn't readily apparent.  Pinging  @apapko @pmdartus @caridy since they previously weighed in.

Before, if someone attempted to mutate a read-only array (using the LWC `@api` decorator, for example), they would be presented with the following error:

```
Error: Invalid mutation: Cannot set "0" on "". "" is read-only.
```

The error now reads:

```
Error: Invalid mutation: Cannot mutate array at index 0.  Array is read-only.
```

The change addresses the specific concern that was raised but may be insufficient to address larger, related DX concerns.  Still, this seemed a reasonable resolution and submitting a PR seemed the easiest to facilitate discussion.  Happy to go in a different direction if that is preferred.

2021-07-22 23:24 UTC, nolanlawson commented on src/read-only-handler.ts
> +            const msg = Array.isArray(originalTarget) ?
You can import `isArray` from the shared module:

https://github.com/salesforce/observable-membrane/blob/5e64a21f4b18a0835515b326fd5aa1ef0cac9baf/src/shared.ts#L26

2021-07-22 23:26 UTC, nolanlawson requested changes
LGTM, just a small nit about `isArray`.

2021-07-23 08:56 UTC, pmdartus approved these changes

2021-07-23 16:15 UTC, kevinv11n requested changes
Nit on formatting, haven't reviewed the logic

2021-07-23 16:15 UTC, kevinv11n commented on src/read-only-handler.ts
> +                `Invalid mutation: Cannot mutate array at index ${key.toString()}.  Array is read-only.` :
Double-space here is inconsistent with other error messages

2021-07-23 19:03 UTC, kevinv11n approved these changes

2021-07-26 08:27 UTC, abdulsattar approved these changes

2021-07-26 19:29 UTC, caridy approved these changes
LGTM

2021-07-26 21:47 UTC, nolanlawson approved these changes

2021-07-26 21:47 UTC, merged